"use client";

import { useState, useEffect } from "react";
import { LoadingSpinner } from "@/components/ui/shared";
import { FileText, User, Calendar, Tag, AlertTriangle, CheckCircle, Info } from "lucide-react";
import { useDashboardStore } from "@/lib/store";

export default function AnalysisPage() {
  const { callAnalyses: analyses, fetchCallAnalyses, isLoading } = useDashboardStore();

  useEffect(() => {
    fetchCallAnalyses();
  }, [fetchCallAnalyses]);

  if (isLoading) return <LoadingSpinner />;

  return (
    <div className="animate-fade-in">
      <div style={{ marginBottom: "28px" }}>
        <h1 style={{ fontSize: "26px", fontWeight: 700 }}>AI Call Analysis</h1>
        <p style={{ color: "var(--text-muted)", fontSize: "14px", marginTop: "4px" }}>
          Detailed AI-generated summaries and sentiment reports for all support calls
        </p>
      </div>

      <div style={{ display: "grid", gap: "20px" }}>
        {analyses.length === 0 ? (
          <div className="glass-card" style={{ padding: "48px", textAlign: "center" }}>
            <FileText size={48} style={{ margin: "0 auto 16px", opacity: 0.2 }} />
            <p style={{ color: "var(--text-muted)" }}>No call analysis reports found.</p>
          </div>
        ) : (
          analyses.map((analysis) => (
            <div key={analysis.id} className="glass-card" style={{ padding: "24px" }}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "20px", alignItems: "flex-start" }}>
                <div style={{ display: "flex", gap: "16px", alignItems: "center" }}>
                  <div style={{ 
                    width: "40px", 
                    height: "40px", 
                    borderRadius: "10px", 
                    background: analysis.resolution_status === "ESCALATED" ? "rgba(239, 68, 68, 0.1)" : "rgba(59, 130, 246, 0.1)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: analysis.resolution_status === "ESCALATED" ? "var(--accent-red)" : "var(--accent-blue)"
                  }}>
                    {analysis.resolution_status === "ESCALATED" ? <AlertTriangle size={20} /> : <CheckCircle size={20} />}
                  </div>
                  <div>
                    <h3 style={{ fontSize: "18px", fontWeight: 600 }}>{analysis.issue_type}</h3>
                    <div style={{ display: "flex", gap: "12px", marginTop: "4px", fontSize: "12px", color: "var(--text-muted)" }}>
                      <span style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                        <Calendar size={12} /> {new Date(analysis.updated_at).toLocaleString()}
                      </span>
                      <span style={{ display: "flex", alignItems: "center", gap: "4px" }}>
                        <Tag size={12} /> {analysis.call_group || "Uncategorized"}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={{ 
                  padding: "4px 12px", 
                  borderRadius: "20px", 
                  fontSize: "12px", 
                  fontWeight: 600,
                  background: analysis.resolution_status === "ESCALATED" ? "var(--accent-red)" : "var(--accent-green)",
                  color: "white"
                }}>
                  {analysis.resolution_status}
                </div>
              </div>

              <div style={{ 
                background: "rgba(0,0,0,0.2)", 
                padding: "20px", 
                borderRadius: "12px", 
                border: "1px solid var(--border-subtle)",
                marginBottom: "20px"
              }}>
                <pre style={{ 
                  whiteSpace: "pre-wrap", 
                  fontFamily: "inherit", 
                  fontSize: "14px", 
                  lineHeight: 1.6,
                  color: "#e2e8f0" 
                }}>
                  {analysis.summary_note || "Summary being generated by AI..."}
                </pre>
              </div>

              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "16px" }}>
                <div style={{ fontSize: "13px" }}>
                  <span style={{ color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Customer ID</span>
                  <span style={{ fontWeight: 500 }}>{analysis.customer_id || "Not Linked"}</span>
                </div>
                <div style={{ fontSize: "13px" }}>
                  <span style={{ color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Order ID</span>
                  <span style={{ fontWeight: 500 }}>{analysis.order_id || "NA"}</span>
                </div>
                <div style={{ fontSize: "13px" }}>
                  <span style={{ color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Sentiment Score</span>
                  <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                    <div style={{ flex: 1, height: "4px", background: "rgba(255,255,255,0.1)", borderRadius: "2px" }}>
                      <div style={{ 
                        width: `${analysis.sentiment_score * 100}%`, 
                        height: "100%", 
                        background: analysis.sentiment_score > 0.6 ? "var(--accent-green)" : analysis.sentiment_score > 0.3 ? "var(--accent-yellow)" : "var(--accent-red)",
                        borderRadius: "2px"
                      }} />
                    </div>
                    <span style={{ fontWeight: 600 }}>{Math.round(analysis.sentiment_score * 100)}%</span>
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
